tap 'homebrew/cask'
tap 'homebrew/cask-eid'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/bundle'

brew 'bash'
brew 'bat'
brew 'exa'
brew 'coreutils'
brew 'git'
brew 'grep'
brew 'mas'
brew 'tree'
brew 'autoconf'
brew 'wxmac'
brew 'openssl'
brew 'gpg'
brew 'openssh-server'
brew 'gpg'
brew 'wget'
brew 'mkcret'
brew 'pyenv'

brew 'asdf'
brew 'postgresql'
brew 'yarn'
brew 'terraform'
brew 'tmux'
brew 'cmake'
brew 'macvim'
brew 'direnv'
brew 'deno'
brew 'nss'
brew 'postgis'

cask 'google-chrome'
cask 'slack'
cask 'virtualbox'
cask 'vlc'
cask 'firefox'

cask 'android-file-transfer'
cask 'visual-studio-code'
cask 'postman'

mas 'Giphy Capture', id: 668208984
